keys:
  - &primary age1984jdrj5uhxwsxre8sqyy5v0lskmh0t2gnm9knyc0wsqpqxy0enskv0msj
creation_rules:
  - path_regex: hosts/laptop/secrets/secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: hosts/server/secrets/secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: hosts/work/secrets/secrets.yaml$
    key_groups:
      - age:
        - *primary
