# ~/.config/hypr/hyprlock.conf

general {
    hide_cursor = true
    grace = 0
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# Fond noir uni (pas de wallpaper)
background {
    monitor =
    color = rgba(10, 10, 15, 1.0)
    path=$HOME/Pictures/wallappers/tuxAscii.png
    brightness=0.6
    blur_size= 5
    blur_passes=2
}

# Heure
label {
    monitor =
    text = $TIME
    color = rgba(220, 220, 220, 1.0)
    font_size = 72
    font_family = JetBrains Mono
    position = 0, 160
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 4
}

# Date
label {
    monitor =
    text = cmd[update:60000] = date "+%A, %d %B %Y"
    color = rgba(160, 160, 160, 1.0)
    font_size = 18
    font_family = JetBrains Mono
    position = 0, 80
    halign = center
    valign = center
}

# Champ de mot de passe
input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    dots_color = rgba(220, 220, 220, 1.0)
    outer_color = rgba(80, 80, 100, 0.8)
    inner_color = rgba(20, 20, 30, 0.9)
    font_color = rgba(220, 220, 220, 1.0)
    fade_on_empty = true
    rounding = 12
    check_color = rgba(100, 200, 150, 1.0)
    fail_color = rgba(200, 80, 80, 1.0)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fail_timeout = 2000
    placeholder_text = <i>Mot de passe...</i>
    position = 0, -30
    halign = center
    valign = center
}

# Message utilisateur
label {
    monitor =
    text = $USER
    color = rgba(80, 80, 95, 1.0)
    font_size = 14
    font_family = JetBrains Mono
    position = 0, 30
    halign = center
    valign = center
}
