# Hyprlauncher is always a daemon. Launching it spawns a daemon that will listen to requests. If launched with hyprlauncher -d, it will not open a window for the first launch.

# To open hyprlauncher, just bind hyprlauncher to a key.

# More information on https://wiki.hypr.land/Hypr-Ecosystem/hyprlauncher/
