-- hyperland.lua
-- This files include other files in folder hyperland. 

-- --------------------------------------------------------------
-- READ THIS !!!!!!!! 
-- Always declare variables before using them (like in programming), Hyprland reads a file from top to bottom — this also applies to source includes, as including a file is like pasting its content at that exact line, so make sure to include your files in the right order.
-- --------------------------------------------------------------

-- Variables
require("hyprland/variables") -- Variables for hyprland conf. Should be called first.

-- Displays 
require("monitors") -- Config monitors. Generated by nwg-displays.
require("workspaces") -- Config workspaces. Generated by nwg-displays.

-- Wallpapers
require("hyprland/wallpaper")

-- Defaults 
require("hyprland/input") -- Inputs and Gesture
require("hyprland/env") -- Environment Variables
require("hyprland/keybinds") -- Keybinds
require("hyprland/apparence") -- Visual appearance and styling (gaps, borders, animations, and decorations).
require("hyprland/rules") -- Window rules
require("hyprland/permissions") -- Process permissions hardening (currently disabled)
require("hyprland/autostart") -- Process launched at session start

-- Plugins 
-- source = waybar/waybar.conf # waybar conf 
