-- Generated by nwg-displays on 2026-08-01 at 15:06:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.01",
    position = "1920x0",
    scale = 1.0,
    mirror = "eDP-1"
})
