keys:
  - &primary age12yvtj49pfh3fqzqflscm0ek4yzrjhr6cqhn7x89gdxnlykq0xudq5c7334
  - &work age1c8pawdsxptfslgrz2c56s39mrtnjzc5mm3hfzgr2wdwu2v6vfsdsupjsq6
creation_rules:
  - path_regex: hosts/laptop/secrets/secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: hosts/server/secrets/secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: hosts/work/secrets/secrets.yaml$
    key_groups:
      - age:
        - *work
        - *primary
