# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a8791708-eebd-4b9b-84e5-ff7a215b217a";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-a8791708-eebd-4b9b-84e5-ff7a215b217a".device = "/dev/disk/by-uuid/a8791708-eebd-4b9b-84e5-ff7a215b217a";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-a8791708-eebd-4b9b-84e5-ff7a215b217a";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-a8791708-eebd-4b9b-84e5-ff7a215b217a";
      fsType = "btrfs";
      options = [ "subvol=home" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E98-2D28";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-40e784fb-5794-4c09-926a-46dd38aa2b11"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
